:source-highlighter: highlight.js
:highlightjs-theme: atom-one-dark-reasonable

== 型別比較 三種不同的comparison operator
    ** strict equality
        *** ===
            **** 這個 operator 在進行比較時不會 perfrom type conversion.
            Conditions::
            . 不同型別 => false
            . 同型別 => same value then true

[source,JavaScript]
----
const num = 0;
const obj = new String("0");
const str = "0";

console.log(num === num); // true
console.log(obj === obj); // true
console.log(str === str); // true

console.log(num === obj); // false
console.log(num === str); // false
console.log(obj === str); // false
console.log(null === undefined); // false
console.log(obj === null); // false
console.log(obj === undefined); // false
----
    ** loose equality
        *** ==
            **** 這個 operator 在進行比較時會 perfrom type conversion. +
             Steps::
            . 如果 operands 是同型別 以下會回 true
            .. Object: reference same object
            .. String: same characters in the same order
            .. Boolean: both true or both false
            .. BigInt: same value
            .. Symbol: same symbol
            .. Number: same value. But NaN on either side will result false.
            . 如其中一個 operands 是 null 或 undefined, 另一側也要是 null 或undefined to return true. Otherwise return false.
            . 如其中一側為 object 另一側為 primitive, convert object to primitive
            . 這一步基本上就是 case by case
            .. Same type => step 1
            .. 一側為 Symbol 另一側不是　=> false
            .. 一側為 Boolean 另一側不是　=> Convert to number, then loosely compare again
            .. 一側為 number 另一側為 String => Convert String to number, failed to convert then NaN
            .. 一側為 number 另一側為 BigInt => compare numeric value
            .. 一側為 String 另一側為 BigInt => Convert String to BigInt then compare
        
[source,JavaScript]
----
const num = 0;
const big = 0n;
const str = "0";
const obj = new String("0");

console.log(num == str); // true
console.log(big == num); // true
console.log(str == big); // true

console.log(num == obj); // true
console.log(big == obj); // true
console.log(str == obj); // true
----

 ** Object.is()
 *** Same Value Equality(同值相等)
    Definition::
        whether two values are functionally identical in all contexts +
        比較兩個值是否功能相同
        
[source,JavaScript]
----
console.log(+0 == -0); // true
console.log(+0 === -0); // true
console.log(Object.is(+0, -0)); // false;

console.log(NaN == NaN); // false
console.log(NaN === NaN); // false
console.log(Object.is(NaN, NaN)); // true

console.log(null == undefined); // true
console.log(null === undefined); // false
console.log(Object.is(null, undefined))// false
----

== this
* Execution Context
** Now what is going on under the hood
* Binding
    ** Default Binding
    *** 當 function 是在普通、未經修飾的情況下被呼叫，也就是當 function 被呼叫的當下如果沒有值的情況下的defauly binding 就是 global object。
    ** Implicit Binding
    *** function 被宣告成為某個物件的參考屬性。在那個 function 被呼叫的當下，該 function 即被那個物件所包含
    ** Explicit Binding
    *** bind() call() apply()
    ** new keyword Binding
    *** 當我們用 new 產生一個新的物件時會自動綁定 this
+
[source,Javascript]
----
function ex(a) {
  this.a = a;
}

var objEx = new ex( 123 );
console.log( objEx.a ); 
----

* This refers to an object instance that contains the current function this resides in.
** what it refers to does not depends on how it is defined not how it is invoked. +
影響 this 的是在於函式的呼叫方法，並非宣告的時機
+
[source,JavaScript]
----
function hello(){
    console.log(this.name);
}

var name = "Ren";
const foo = {
    name: "Jack",
    hello: hello
}

hello() //Ren
foo.hello() //Jack
----
+
[source,JavaScript]
----
function showName(){
    console.log(this.name);
}

var name = "Jeff";
const foo = {
    name: "Bob",
    showName: showName
}

printName = foo.showName;
printName();
----

** 不同 method 在不同 object 會有不同的結論
+
[source,JavaScript]
function getThis() {
  return this;
}
const obj1 = { name: "obj1" };
const obj2 = { name: "obj2" };
obj1.getThis = getThis;
obj2.getThis = getThis;
console.log(obj1.getThis()); // { name: 'obj1', getThis: [Function: getThis] }
console.log(obj2.getThis()); // { name: 'obj2', getThis: [Function: getThis] }


* 如 this 被呼叫的 function 不指向特定的物件時，this 會 refer to global object.
    ** Node.js & Browser under strict mode both will refer to undefined
    ** Under non-strict mode, browser will refers to window
    ** Under non-strict mode, node.js will refers to global

== Callback
* 在 Callback 的情況下，同理記得剛剛說的: +
    _影響 this 的是在於函式的呼叫方法，並非宣告的時機_
+
[source,JavaScript]
----
function t0() {
    console.log(this.d)
}

var d = 'beagles'

var obj0 = {
    d: 'dachshund',
    t0:t0
}

function cbTest(fn){
    fn()
}
cbTest(obj0.t0);
----
+
[source,JavaScript]
----
var input = 1;
function square() { 
 let cbFn = function(){ console.log(this.input*this.input) };
 setTimeout( cbFn , 1000);
};
var obj = {
 input : 3,
 square: square
};
obj.square(); // 1
----
* What happened?


== Arrow Function
*  arrow function 它本身不會去 bind 一個scope，而是會lexcial binding 去往外去找它的 scope。
+
[source,JavaScript]
----
const o = {
    value: 42,
    regularFunction: function() {
        console.log('Regular function:', this.value); // `this` refers to `obj`
    },
    arrowFunction: () => {
        console.log('Arrow function:', this.value); // `this` refers to the global object
    }
};

o.regularFunction(); // Output: Regular function: 42
o.arrowFunction();   // Output: Arrow function: undefined (or global.value if defined)
----
+
[source,JavaScript]
----
const obj = {
  count: 10,
  doSomethingLater() {
    setTimeout(function () {
      // the function executes on the window scope
      this.count++;
      console.log(this.count);
    }, 300);
  },
};

obj.doSomethingLater(); // logs "NaN", because the property "count" is not in the window scope.
----
+
[source,Javascript]
----
const obj = {
  count: 10,
  doSomethingLater() {
    // The method syntax binds "this" to the "obj" context.
    setTimeout(() => {
      // Since the arrow function doesn't have its own binding and
      // setTimeout (as a function call) doesn't create a binding
      // itself, the "obj" context of the outer method is used.
      this.count++;
      console.log(this.count);
    }, 300);
  },
};

obj.doSomethingLater(); // logs 11
----

== 更改 this 的值
* Let's take a look at something first
+
[source,Javascript]
----
function t1() {
    console.log(this.dog)
}

var dog = 'husky'

var obj1 = {
    dog: 'pubs',
    t1:t1
}

var alien = obj1.t1
alien() 
----

* Call, Apply, Bind
    ** call(): 以給予的 this value 及 arguments 去呼叫該 function +
    Usage:: call(obj,args1,args2....)
    ** apply(): 如同 call, 但給予的 arguments 為 array +
    Usage:: apply(obj, [args1,args2..])
    ** bindWIP(): 回傳一個新的 function 且用提供的 this 去執行該 function +
    Usage:: bind(obj,args1,args2...)
+
[source,Javascript]
----
function cab() { 
  console.log(this.key);
}
var objA = { key : "A" };
var objB = { key : "B" };

cab.call(objA) // A
cab.apply(objB) // B

var bindedcab = cab.bind(objA);
bindedcab(); // A;
var doubleBindedcab = bindedcab.bind(objB);
doubleBindedcab() // A (Once binded the value of this can't be changed)
----
* 常見的使用情形
** 按下按鈕後執行 ajax，但在 callback function 的 this 卻不是你想像中的那樣
+
[source, JavaScript]
----
// button & click event.
var el = document.getElementById("btn");

el.addEventListener("click", function(event) {
  console.log( this.textContent );

  $ajax('[URL]', function(res) {
    // this.textContent => undefined
    console.log(this.textContent, res);
  });
}, false);
----
** we can rewrite it with bind
+
[source,Javascript]
----
el.addEventListener("click", function(event) {
  console.log( this.textContent );

  // 透過 bind(this) 來強制指定該 function scope 的 this
  $ajax('[URL]', function(res) {
    console.log(this.textContent, res);
  }.bind(this));

}, false);
----

== this in Jquery
* this
** 使用上跟JS一樣， 一樣會指向所屬的 object instance
+
[source,Javascript]
----
const obj = {
    name: "hrithik",
    roll: 36,
    mydata: function () {
        return this.name;
    }
}
document.getElementById("paraID")
    .innerHTML = obj.mydata();
----
+
[source,Javascript]
----
$("#clickme").click(function () {
    this.style.color = "green"
    })
----
* $(this)
** 一樣會指向所屬的 object instance，但 $(this) 是一個 Jquery object 就可以使用 Jquery 的 function and methods。
+
[source,Javascript]
----
$(".div1").click(function () {
    
    $(this).hide();
});
----

